server:
  port: 8888
  ssl:
    enabled: true
    key-store: classpath:cloud_config_server_keyStore.jks
    key-store-password: password
    key-alias: cloud-config-server
    key-store-type: JKS
    trust-store: classpath:cloud_config_server_trustedStore.jks
    trust-store-password: password
    trust-store-type: JKS
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh, refresh

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          clone-on-start: true
          search-paths: /config/{application}
          uri: https://github.com/vesnamilic/configuration-repository.git
