eureka:
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9996

#Spring DataSource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sep-project 
    username: postgres
    password: root
    initialization-mode: always  
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
