server:
  port: 9996
  ssl:
    enabled: true
    key-store: classpath:client_service_keyStore.jks
    key-store-password: password
    key-alias: client-service
    key-store-type: JKS
    trust-store: classpath:client_service_trustedStore.jks
    trust-store-password: password
    trust-store-type: JKS
    
eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


#Spring DataSource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sep-project 
    username: postgres
    password: root
    initialization-mode: always  
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  mail:
    host: smtp.gmail.com
    username : timisaprojekat@gmail.com
    password : isaprojekat.22
    port : 587
    properties:
      mail:
        smtp:
          starttls:
            enable : true
          ssl:
            trust: smtp.gmail.com
