server:
  port: 8763
  ssl:
    enabled: true
    key-store: classpath:zuul_gateway_keyStore.jks
    key-store-password: password
    key-alias: zuul-gateway
    trust-store: classpath:zuul_gateway_trustedStore.jks
    trust-store-password: password
    trust-store-type: JKS
  
eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true


zuul:
  prefix: /api
  routes:
    bank-service:
      service-id: bank-service
      path: "/bank/**"
      sensitive-headers: Cookie,Set-Cookie
    payPal-service:
      path: "/paypal/**"
      service-id: paypal-service
      sensitive-headers: Cookie,Set-Cookie
    client-service:
      path: "/client/**"
      service-id: client-service
      sensitive-headers: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
   
