eureka:
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9993
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest