server:
  port: 9993
  ssl:
    enabled: true
    key-store: classpath:paypal_service_keyStore.jks
    key-store-password: password
    key-alias: paypal-service
    key-store-type: JKS
    trust-store: classpath:paypal_service_trustedStore.jks
    trust-store-password: password
    trust-store-type: JKS

eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    

management:
  endpoints:
    web:
      exposure:
        include: '*'
  
spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/sep-paypal 
    username: postgres
    password: root
    initialization-mode: always  
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        
success_url : "https://localhost:8762/api/paypal/complete?email="
cancel_url : "https://localhost:4200/#/cancel"
error_url : "https://localhost:4200/#/error"

success_url_redirect : "https://localhost:4200/#/success"
