server:
  port: 9994
  ssl:
    enabled: true
    key-store: classpath:mock_payment_service_keyStore.jks
    key-store-password: password
    key-alias: mock-payment-service
    key-store-type: JKS
    trust-store: classpath:mock_payment_service_trustedStore.jks
    trust-store-password: password
    trust-store-type: JKS

eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    

management:
  endpoints:
    web:
      exposure:
        include: '*'
  
spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/mock-payment
    username: postgres
    password: root
    initialization-mode: always  
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
      