eureka:
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: ${PORT:0}


    